import { DataSource } from 'typeorm';
import { Commune } from '../entities/commune.entity';
import { Region } from '../../regions/entities/region.entity';
import { Street } from '../../streets/entities/street.entity';
import { StreetNumber } from '../../street-numbers/entities/street-number.entity';
import { normalizeText } from '../../utils/normalize-text.util';

const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST ?? 'localhost',
  port: parseInt(process.env.DB_PORT ?? '5432', 10),
  username: process.env.DB_USERNAME ?? 'postgres',
  password: process.env.DB_PASSWORD ?? 'postgres',
  database: process.env.DB_NAME ?? 'postal_codes',
  entities: [Commune, Region, Street, StreetNumber],
  synchronize: false,
  logging: false,
});

const communesSeed = [
  { name: 'Arica', regionNumber: 15 },
  { name: 'Camarones', regionNumber: 15 },
  { name: 'Putre', regionNumber: 15 },
  { name: 'General Lagos', regionNumber: 15 },
  { name: 'Iquique', regionNumber: 1 },
  { name: 'Alto Hospicio', regionNumber: 1 },
  { name: 'Pozo Almonte', regionNumber: 1 },
  { name: 'Camiña', regionNumber: 1 },
  { name: 'Colchane', regionNumber: 1 },
  { name: 'Huara', regionNumber: 1 },
  { name: 'Pica', regionNumber: 1 },
  { name: 'Antofagasta', regionNumber: 2 },
  { name: 'Mejillones', regionNumber: 2 },
  { name: 'Sierra Gorda', regionNumber: 2 },
  { name: 'Taltal', regionNumber: 2 },
  { name: 'Calama', regionNumber: 2 },
  { name: 'Ollagüe', regionNumber: 2 },
  { name: 'San Pedro de Atacama', regionNumber: 2 },
  { name: 'Tocopilla', regionNumber: 2 },
  { name: 'María Elena', regionNumber: 2 },
  { name: 'Copiapó', regionNumber: 3 },
  { name: 'Caldera', regionNumber: 3 },
  { name: 'Tierra Amarilla', regionNumber: 3 },
  { name: 'Chañaral', regionNumber: 3 },
  { name: 'Diego de Almagro', regionNumber: 3 },
  { name: 'Vallenar', regionNumber: 3 },
  { name: 'Alto del Carmen', regionNumber: 3 },
  { name: 'Freirina', regionNumber: 3 },
  { name: 'Huasco', regionNumber: 3 },
  { name: 'La Serena', regionNumber: 4 },
  { name: 'Coquimbo', regionNumber: 4 },
  { name: 'Andacollo', regionNumber: 4 },
  { name: 'La Higuera', regionNumber: 4 },
  { name: 'Paihuano', regionNumber: 4 },
  { name: 'Vicuña', regionNumber: 4 },
  { name: 'Illapel', regionNumber: 4 },
  { name: 'Canela', regionNumber: 4 },
  { name: 'Los Vilos', regionNumber: 4 },
  { name: 'Salamanca', regionNumber: 4 },
  { name: 'Ovalle', regionNumber: 4 },
  { name: 'Combarbalá', regionNumber: 4 },
  { name: 'Monte Patria', regionNumber: 4 },
  { name: 'Punitaqui', regionNumber: 4 },
  { name: 'Río Hurtado', regionNumber: 4 },
  { name: 'Valparaíso', regionNumber: 5 },
  { name: 'Casablanca', regionNumber: 5 },
  { name: 'Concón', regionNumber: 5 },
  { name: 'Juan Fernández', regionNumber: 5 },
  { name: 'Puchuncaví', regionNumber: 5 },
  { name: 'Quintero', regionNumber: 5 },
  { name: 'Viña del Mar', regionNumber: 5 },
  { name: 'Isla de Pascua', regionNumber: 5 },
  { name: 'Los Andes', regionNumber: 5 },
  { name: 'Calle Larga', regionNumber: 5 },
  { name: 'Rinconada', regionNumber: 5 },
  { name: 'San Esteban', regionNumber: 5 },
  { name: 'La Ligua', regionNumber: 5 },
  { name: 'Cabildo', regionNumber: 5 },
  { name: 'Papudo', regionNumber: 5 },
  { name: 'Petorca', regionNumber: 5 },
  { name: 'Zapallar', regionNumber: 5 },
  { name: 'Quillota', regionNumber: 5 },
  { name: 'La Calera', regionNumber: 5 },
  { name: 'Hijuelas', regionNumber: 5 },
  { name: 'La Cruz', regionNumber: 5 },
  { name: 'Nogales', regionNumber: 5 },
  { name: 'San Antonio', regionNumber: 5 },
  { name: 'Algarrobo', regionNumber: 5 },
  { name: 'Cartagena', regionNumber: 5 },
  { name: 'El Quisco', regionNumber: 5 },
  { name: 'El Tabo', regionNumber: 5 },
  { name: 'Santo Domingo', regionNumber: 5 },
  { name: 'San Felipe', regionNumber: 5 },
  { name: 'Catemu', regionNumber: 5 },
  { name: 'Llay-Llay', regionNumber: 5 },
  { name: 'Panquehue', regionNumber: 5 },
  { name: 'Putaendo', regionNumber: 5 },
  { name: 'Santa María', regionNumber: 5 },
  { name: 'Quilpué', regionNumber: 5 },
  { name: 'Limache', regionNumber: 5 },
  { name: 'Olmué', regionNumber: 5 },
  { name: 'Villa Alemana', regionNumber: 5 },
  { name: 'Rancagua', regionNumber: 6 },
  { name: 'Codegua', regionNumber: 6 },
  { name: 'Coinco', regionNumber: 6 },
  { name: 'Coltauco', regionNumber: 6 },
  { name: 'Doñihue', regionNumber: 6 },
  { name: 'Graneros', regionNumber: 6 },
  { name: 'Las Cabras', regionNumber: 6 },
  { name: 'Machalí', regionNumber: 6 },
  { name: 'Malloa', regionNumber: 6 },
  { name: 'Mostazal', regionNumber: 6 },
  { name: 'Olivar', regionNumber: 6 },
  { name: 'Peumo', regionNumber: 6 },
  { name: 'Pichidegua', regionNumber: 6 },
  { name: 'Quinta de Tilcoco', regionNumber: 6 },
  { name: 'Rengo', regionNumber: 6 },
  { name: 'Requínoa', regionNumber: 6 },
  { name: 'San Vicente', regionNumber: 6 },
  { name: 'Pichilemu', regionNumber: 6 },
  { name: 'La Estrella', regionNumber: 6 },
  { name: 'Litueche', regionNumber: 6 },
  { name: 'Marchigüe', regionNumber: 6 },
  { name: 'Navidad', regionNumber: 6 },
  { name: 'Paredones', regionNumber: 6 },
  { name: 'San Fernando', regionNumber: 6 },
  { name: 'Chépica', regionNumber: 6 },
  { name: 'Chimbarongo', regionNumber: 6 },
  { name: 'Lolol', regionNumber: 6 },
  { name: 'Nancagua', regionNumber: 6 },
  { name: 'Palmilla', regionNumber: 6 },
  { name: 'Peralillo', regionNumber: 6 },
  { name: 'Placilla', regionNumber: 6 },
  { name: 'Pumanque', regionNumber: 6 },
  { name: 'Santa Cruz', regionNumber: 6 },
  { name: 'Talca', regionNumber: 7 },
  { name: 'Constitución', regionNumber: 7 },
  { name: 'Curepto', regionNumber: 7 },
  { name: 'Empedrado', regionNumber: 7 },
  { name: 'Maule', regionNumber: 7 },
  { name: 'Pelarco', regionNumber: 7 },
  { name: 'Pencahue', regionNumber: 7 },
  { name: 'Río Claro', regionNumber: 7 },
  { name: 'San Clemente', regionNumber: 7 },
  { name: 'San Rafael', regionNumber: 7 },
  { name: 'Cauquenes', regionNumber: 7 },
  { name: 'Chanco', regionNumber: 7 },
  { name: 'Pelluhue', regionNumber: 7 },
  { name: 'Curicó', regionNumber: 7 },
  { name: 'Hualañé', regionNumber: 7 },
  { name: 'Licantén', regionNumber: 7 },
  { name: 'Molina', regionNumber: 7 },
  { name: 'Rauco', regionNumber: 7 },
  { name: 'Romeral', regionNumber: 7 },
  { name: 'Sagrada Familia', regionNumber: 7 },
  { name: 'Teno', regionNumber: 7 },
  { name: 'Vichuquén', regionNumber: 7 },
  { name: 'Linares', regionNumber: 7 },
  { name: 'Colbún', regionNumber: 7 },
  { name: 'Longaví', regionNumber: 7 },
  { name: 'Parral', regionNumber: 7 },
  { name: 'Retiro', regionNumber: 7 },
  { name: 'San Javier', regionNumber: 7 },
  { name: 'Villa Alegre', regionNumber: 7 },
  { name: 'Yerbas Buenas', regionNumber: 7 },
  { name: 'Chillán', regionNumber: 16 },
  { name: 'Bulnes', regionNumber: 16 },
  { name: 'Chillán Viejo', regionNumber: 16 },
  { name: 'El Carmen', regionNumber: 16 },
  { name: 'Pemuco', regionNumber: 16 },
  { name: 'Pinto', regionNumber: 16 },
  { name: 'Quillón', regionNumber: 16 },
  { name: 'San Ignacio', regionNumber: 16 },
  { name: 'Yungay', regionNumber: 16 },
  { name: 'Quirihue', regionNumber: 16 },
  { name: 'Cobquecura', regionNumber: 16 },
  { name: 'Coelemu', regionNumber: 16 },
  { name: 'Ninhue', regionNumber: 16 },
  { name: 'Portezuelo', regionNumber: 16 },
  { name: 'Ránquil', regionNumber: 16 },
  { name: 'Treguaco', regionNumber: 16 },
  { name: 'San Carlos', regionNumber: 16 },
  { name: 'Coihueco', regionNumber: 16 },
  { name: 'Ñiquén', regionNumber: 16 },
  { name: 'San Fabián', regionNumber: 16 },
  { name: 'San Nicolás', regionNumber: 16 },
  { name: 'Concepción', regionNumber: 8 },
  { name: 'Coronel', regionNumber: 8 },
  { name: 'Chiguayante', regionNumber: 8 },
  { name: 'Florida', regionNumber: 8 },
  { name: 'Hualqui', regionNumber: 8 },
  { name: 'Lota', regionNumber: 8 },
  { name: 'Penco', regionNumber: 8 },
  { name: 'San Pedro de La Paz', regionNumber: 8 },
  { name: 'Santa Juana', regionNumber: 8 },
  { name: 'Talcahuano', regionNumber: 8 },
  { name: 'Tomé', regionNumber: 8 },
  { name: 'Hualpén', regionNumber: 8 },
  { name: 'Lebu', regionNumber: 8 },
  { name: 'Arauco', regionNumber: 8 },
  { name: 'Cañete', regionNumber: 8 },
  { name: 'Contulmo', regionNumber: 8 },
  { name: 'Curanilahue', regionNumber: 8 },
  { name: 'Los Álamos', regionNumber: 8 },
  { name: 'Tirúa', regionNumber: 8 },
  { name: 'Los Ángeles', regionNumber: 8 },
  { name: 'Antuco', regionNumber: 8 },
  { name: 'Cabrero', regionNumber: 8 },
  { name: 'Laja', regionNumber: 8 },
  { name: 'Mulchén', regionNumber: 8 },
  { name: 'Nacimiento', regionNumber: 8 },
  { name: 'Negrete', regionNumber: 8 },
  { name: 'Quilaco', regionNumber: 8 },
  { name: 'Quilleco', regionNumber: 8 },
  { name: 'San Rosendo', regionNumber: 8 },
  { name: 'Santa Bárbara', regionNumber: 8 },
  { name: 'Tucapel', regionNumber: 8 },
  { name: 'Yumbel', regionNumber: 8 },
  { name: 'Alto Biobío', regionNumber: 8 },
  { name: 'Temuco', regionNumber: 9 },
  { name: 'Carahue', regionNumber: 9 },
  { name: 'Cunco', regionNumber: 9 },
  { name: 'Curarrehue', regionNumber: 9 },
  { name: 'Freire', regionNumber: 9 },
  { name: 'Galvarino', regionNumber: 9 },
  { name: 'Gorbea', regionNumber: 9 },
  { name: 'Lautaro', regionNumber: 9 },
  { name: 'Loncoche', regionNumber: 9 },
  { name: 'Melipeuco', regionNumber: 9 },
  { name: 'Nueva Imperial', regionNumber: 9 },
  { name: 'Padre Las Casas', regionNumber: 9 },
  { name: 'Perquenco', regionNumber: 9 },
  { name: 'Pitrufquén', regionNumber: 9 },
  { name: 'Pucón', regionNumber: 9 },
  { name: 'Saavedra', regionNumber: 9 },
  { name: 'Teodoro Schmidt', regionNumber: 9 },
  { name: 'Toltén', regionNumber: 9 },
  { name: 'Vilcún', regionNumber: 9 },
  { name: 'Villarrica', regionNumber: 9 },
  { name: 'Cholchol', regionNumber: 9 },
  { name: 'Angol', regionNumber: 9 },
  { name: 'Collipulli', regionNumber: 9 },
  { name: 'Curacautín', regionNumber: 9 },
  { name: 'Ercilla', regionNumber: 9 },
  { name: 'Lonquimay', regionNumber: 9 },
  { name: 'Los Sauces', regionNumber: 9 },
  { name: 'Lumaco', regionNumber: 9 },
  { name: 'Purén', regionNumber: 9 },
  { name: 'Renaico', regionNumber: 9 },
  { name: 'Traiguén', regionNumber: 9 },
  { name: 'Victoria', regionNumber: 9 },
  { name: 'Valdivia', regionNumber: 14 },
  { name: 'Corral', regionNumber: 14 },
  { name: 'Lanco', regionNumber: 14 },
  { name: 'Los Lagos', regionNumber: 14 },
  { name: 'Máfil', regionNumber: 14 },
  { name: 'Mariquina', regionNumber: 14 },
  { name: 'Paillaco', regionNumber: 14 },
  { name: 'Panguipulli', regionNumber: 14 },
  { name: 'La Unión', regionNumber: 14 },
  { name: 'Futrono', regionNumber: 14 },
  { name: 'Lago Ranco', regionNumber: 14 },
  { name: 'Río Bueno', regionNumber: 14 },
  { name: 'Puerto Montt', regionNumber: 10 },
  { name: 'Calbuco', regionNumber: 10 },
  { name: 'Cochamó', regionNumber: 10 },
  { name: 'Fresia', regionNumber: 10 },
  { name: 'Frutillar', regionNumber: 10 },
  { name: 'Los Muermos', regionNumber: 10 },
  { name: 'Llanquihue', regionNumber: 10 },
  { name: 'Maullín', regionNumber: 10 },
  { name: 'Puerto Varas', regionNumber: 10 },
  { name: 'Castro', regionNumber: 10 },
  { name: 'Ancud', regionNumber: 10 },
  { name: 'Chonchi', regionNumber: 10 },
  { name: 'Curaco de Vélez', regionNumber: 10 },
  { name: 'Dalcahue', regionNumber: 10 },
  { name: 'Puqueldón', regionNumber: 10 },
  { name: 'Queilén', regionNumber: 10 },
  { name: 'Quellón', regionNumber: 10 },
  { name: 'Quemchi', regionNumber: 10 },
  { name: 'Quinchao', regionNumber: 10 },
  { name: 'Osorno', regionNumber: 10 },
  { name: 'Puerto Octay', regionNumber: 10 },
  { name: 'Purranque', regionNumber: 10 },
  { name: 'Puyehue', regionNumber: 10 },
  { name: 'Río Negro', regionNumber: 10 },
  { name: 'San Juan de la Costa', regionNumber: 10 },
  { name: 'San Pablo', regionNumber: 10 },
  { name: 'Chaitén', regionNumber: 10 },
  { name: 'Futaleufú', regionNumber: 10 },
  { name: 'Hualaihué', regionNumber: 10 },
  { name: 'Palena', regionNumber: 10 },
  { name: 'Coyhaique', regionNumber: 11 },
  { name: 'Lago Verde', regionNumber: 11 },
  { name: 'Aysén', regionNumber: 11 },
  { name: 'Cisnes', regionNumber: 11 },
  { name: 'Guaitecas', regionNumber: 11 },
  { name: 'Cochrane', regionNumber: 11 },
  { name: "O'Higgins", regionNumber: 11 },
  { name: 'Tortel', regionNumber: 11 },
  { name: 'Chile Chico', regionNumber: 11 },
  { name: 'Río Ibáñez', regionNumber: 11 },
  { name: 'Punta Arenas', regionNumber: 12 },
  { name: 'Laguna Blanca', regionNumber: 12 },
  { name: 'Río Verde', regionNumber: 12 },
  { name: 'San Gregorio', regionNumber: 12 },
  { name: 'Cabo de Hornos', regionNumber: 12 },
  { name: 'Antártica', regionNumber: 12 },
  { name: 'Porvenir', regionNumber: 12 },
  { name: 'Primavera', regionNumber: 12 },
  { name: 'Timaukel', regionNumber: 12 },
  { name: 'Natales', regionNumber: 12 },
  { name: 'Torres del Paine', regionNumber: 12 },
  { name: 'Santiago', regionNumber: 13 },
  { name: 'Cerrillos', regionNumber: 13 },
  { name: 'Cerro Navia', regionNumber: 13 },
  { name: 'Conchalí', regionNumber: 13 },
  { name: 'El Bosque', regionNumber: 13 },
  { name: 'Estación Central', regionNumber: 13 },
  { name: 'Huechuraba', regionNumber: 13 },
  { name: 'Independencia', regionNumber: 13 },
  { name: 'La Cisterna', regionNumber: 13 },
  { name: 'La Florida', regionNumber: 13 },
  { name: 'La Granja', regionNumber: 13 },
  { name: 'La Pintana', regionNumber: 13 },
  { name: 'La Reina', regionNumber: 13 },
  { name: 'Las Condes', regionNumber: 13 },
  { name: 'Lo Barnechea', regionNumber: 13 },
  { name: 'Lo Espejo', regionNumber: 13 },
  { name: 'Lo Prado', regionNumber: 13 },
  { name: 'Macul', regionNumber: 13 },
  { name: 'Maipú', regionNumber: 13 },
  { name: 'Ñuñoa', regionNumber: 13 },
  { name: 'Pedro Aguirre Cerda', regionNumber: 13 },
  { name: 'Peñalolén', regionNumber: 13 },
  { name: 'Providencia', regionNumber: 13 },
  { name: 'Pudahuel', regionNumber: 13 },
  { name: 'Quilicura', regionNumber: 13 },
  { name: 'Quinta Normal', regionNumber: 13 },
  { name: 'Recoleta', regionNumber: 13 },
  { name: 'Renca', regionNumber: 13 },
  { name: 'San Joaquín', regionNumber: 13 },
  { name: 'San Miguel', regionNumber: 13 },
  { name: 'San Ramón', regionNumber: 13 },
  { name: 'Vitacura', regionNumber: 13 },
  { name: 'Puente Alto', regionNumber: 13 },
  { name: 'Pirque', regionNumber: 13 },
  { name: 'San José de Maipo', regionNumber: 13 },
  { name: 'Colina', regionNumber: 13 },
  { name: 'Lampa', regionNumber: 13 },
  { name: 'Til Til', regionNumber: 13 },
  { name: 'San Bernardo', regionNumber: 13 },
  { name: 'Buin', regionNumber: 13 },
  { name: 'Calera de Tango', regionNumber: 13 },
  { name: 'Paine', regionNumber: 13 },
  { name: 'Melipilla', regionNumber: 13 },
  { name: 'Alhué', regionNumber: 13 },
  { name: 'Curacaví', regionNumber: 13 },
  { name: 'María Pinto', regionNumber: 13 },
  { name: 'San Pedro', regionNumber: 13 },
  { name: 'Talagante', regionNumber: 13 },
  { name: 'El Monte', regionNumber: 13 },
  { name: 'Isla de Maipo', regionNumber: 13 },
  { name: 'Padre Hurtado', regionNumber: 13 },
  { name: 'Peñaflor', regionNumber: 13 },
];

async function seedCommunes() {
  await AppDataSource.initialize();
  const communeRepo = AppDataSource.getRepository(Commune);
  const regionRepo = AppDataSource.getRepository(Region);

  const communesByRegion = communesSeed.reduce(
    (acc, commune) => {
      acc[commune.regionNumber] = acc[commune.regionNumber] || [];
      acc[commune.regionNumber].push(commune);
      return acc;
    },
    {} as Record<number, typeof communesSeed>,
  );

  for (const [regionNumberStr, communes] of Object.entries(communesByRegion)) {
    const regionNumber = parseInt(regionNumberStr, 10);
    const region = await regionRepo.findOne({
      where: { number: regionNumber },
    });

    if (!region) {
      console.warn(
        `⛔ Region ${regionNumber} not found. Skipping ${communes.length} communes.`,
      );
      continue;
    }

    const existingCommunes = await communeRepo.find({
      where: { regionId: region.id },
      select: ['name'],
    });

    const existingCommuneNames = new Set(
      existingCommunes.map((c) => c.name.toLowerCase()),
    );

    const communesToInsert = communes.filter(
      (commune) => !existingCommuneNames.has(commune.name.toLowerCase()),
    );

    if (communesToInsert.length > 0) {
      await communeRepo.insert(
        communesToInsert.map((commune) => ({
          name: commune.name,
          normalizedName: normalizeText(commune.name),
          regionId: region.id,
          isActive: true,
        })),
      );
      console.log(
        `✅ Inserted ${communesToInsert.length} communes into ${region.label}.`,
      );
    } else {
      console.log(`⏩ All communes for ${region.label} already exist.`);
    }
  }

  await AppDataSource.destroy();
  console.log('🌱 Commune seeding completed.');
}

seedCommunes().catch((error) => {
  console.error('❌ Error during commune seeding:', error);
  process.exit(1);
});
